name = "dice-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-12-04"
compatibility_flags = ["nodejs_compat"]

# Durable Objects configuration
[[durable_objects.bindings]]
name = "SSE_CONNECTIONS"
class_name = "SSEConnectionDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["SSEConnectionDurableObject"]


# Optional: Custom domain configuration
[env.production]
routes = [
  { pattern = "dice.sebastian.software/*", zone_name = "sebastian.software" }
]

# Development settings
[dev]
port = 8787
local_protocol = "http"
