name = "dice-mcp-server"
main = "src/index.ts"
account_id = "4c82769bc8b746a321b75014c6983bb8"
compatibility_date = "2024-12-04"
compatibility_flags = ["nodejs_compat"]

# KV Namespace - will be created during setup
[[kv_namespaces]]
binding = "DICE_KV"
id = "c87cf7076b9f4d1793bccc59a9f762cd"

# Custom domain configuration
[env.production]
routes = [
  { pattern = "dice.sebastian.software/*", zone_name = "sebastian.software" }
]

[dev]
port = 8787
local_protocol = "http"
