name: Deploy to Cloudflare Workers

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug - Check authentication
        run: |
          if [ -n "${{ secrets.CLOUDFLARE_API_TOKEN }}" ]; then
            echo "✅ Secret is set"
            echo "Length: ${#CLOUDFLARE_API_TOKEN}"
          else
            echo "❌ Secret is NOT set"
          fi
          npx wrangler whoami
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
